# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8858a866f7003d883c1a1bceff04bcf2be307f67fe752754818dc881703c10e5b5d076972042e518ab004cc0ea82fc3e3e8889b305154d66637cc7ed22c6f99

test:
  secret_key_base: 9ca8c4ea7ea57298ed89b1fd0b065fb49f32f73b10833d9a50848c9e8282fa5181743b25db32afc19a47ded532e20d689433219bfefafe1e431cdd526997692b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
